// This file was autogenerated by calcdeps.py
goog.addDependency("../../../js/org/koshinuke/positioning/gravityposition.js", ['org.koshinuke.positioning.GravityPosition'], ['goog.positioning.AbstractPosition']);
goog.addDependency("../../../js/org/koshinuke/template/breadcrumb.js", ['org.koshinuke.template.breadcrumb'], ['soy', 'soy.StringBuilder']);
goog.addDependency("../../../js/org/koshinuke/ui/Breadcrumb.js", ['org.koshinuke.ui.Breadcrumb'], ['goog.array', 'goog.dom', 'goog.soy']);
